import os
import time
os.system("clear")
print("\033[0;91m╔████████████"+"\033[0;92m▒▒▒▒▒▒▒▒▒▒▒▒▒▒"+"\033[0;93m████████████╗")
l = input("\033[0;91mCreat Your Name~» ")
nam = input("\033[0;92mCreat Your Password~» ")
acc=(l,nam)
os.system("clear")
time.sleep(.3)
print("\033[0;91m╔████████████"+"\033[0;92m▒▒▒▒▒▒▒▒▒▒▒▒▒▒"+"\033[0;93m████████████╗")
pa=input("your Name:» ")
na=input("your Password:» ")
nt=(pa,na)
if acc != nt :
    os.system("xdg-open https://youtube.com/channel/UC8AxGnNNu8M4Q4fM0trOYyQ")
    time.sleep(.3)
    breack
    na="lwes eltasa hsck"
    print("tool admin")
else:
    time.sleep(.3)
    print("\033[0;92mlogin succes !")
    time.sleep(1)
    print ("\033[0;92mwelcome "+na)
    time.sleep(1)
co=("\033[0;92m")
lor=("\033[0;33m")
os.system("clear")
time.sleep(.2)
print(lor,"loding",co,"10% ▁")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"15% ▁")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"20% ▁▁")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"25% ▁▁▂")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"30% ▁▁▂▂")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"35% ▁▁▂▂▃")
time.sleep(1)
os.system('clear')
print(lor,"loding",co,"40% ▁▁▂▂▃▃")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"45% ▁▁▂▂▃▃▄")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"50% ▁▁▂▂▃▃▄▄")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"55% ▁▁▂▂▃▃▄▄▅")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"60% ▁▁▂▂▃▃▄▄▅▅")
time.sleep(1)
os.system("clear")
print (lor,"loding",co,"65% ▁▁▂▂▃▃▄▄▅▅▆")
time.sleep(1)
os.system("clear")
print (lor,"loding",co,"70% ▁▁▂▂▃▃▄▄▅▅▆▆")
time.sleep(1)
os.system("clear")
print (lor,"loding",co,"75% ▁▁▂▂▃▃▄▄▅▅▆▆▇")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"80% ▁▁▂▂▃▃▄▄▅▅▆▆▇▇")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"85% ▁▁▂▂▃▃▄▄▅▅▆▆▇▇█")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"90% ▁▁▂▂▃▃▄▄▅▅▆▆▇▇██")
time.sleep(1)
os.system("clear")
print(lor,"loding",co,"99% ▁▁▂▂▃▃▄▄▅▅▆▆▇▇███")
time.sleep(1)
os.system("clear")
print("\033[0;32mdone !",co,"100%")
time.sleep(1)
os.system("clear")

time.sleep(1)

print ("\033[0;91m╔████████████"+"\033[0;92m▒▒▒▒▒▒▒▒▒▒▒▒▒▒"+"\033[0;93m████████████╗")

l1=("\033[0;91m▌│█║▌║▌║║▌║▌║█│▌│█║▌║▌║║▌║▌║█│▌▌")
l2=("\033[0;92m▌│█║▌║▌║║▌║▌║█│▌│█║▌║▌║║▌║▌║█│▌▌")
l3=("\033[0;93m▌│█║▌║▌║║▌║▌║█│▌│█║▌║▌║║▌║▌║█│▌▌")

print ('''\033[0;91m
﴾ insagram & facebook & gmail password cracker script
''')
print(l1)
print ('''
\033[0;92mdiv by : 𝑳𝑾𝑬𝑺 𝑬𝑳𝑻𝑨𝑺𝑨 𝑯𝑨𝑪𝑲 (LEH)
''')
print(l2)
print ('''\033[0;93m
Facebook : Abdelrahman M. Fiala''')
print(l3)
print('''\033[0;
instagram : Abdelrahman.Fiala﴿
''')
print ('''\033[0;91m
  
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▒▒▒▒▒▒▒
▒▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░▄░░▒▒▒▒▒
▒▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░██▌░░▒▒▒▒
▒▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░▄▄███▀░░░░▒▒▒
▒▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░░█████░▄█░░░░▒▒
▒▒░░░░░░░░░░░░░░░░░░░░░░░░░░▄████████▀░░░░▒▒
▒▒░░░░░░░░░░░░░░░░░░░░░░░░▄█████████░░░░░░░▒
▒░░░░░░░░░░░░░░░░░░░░░░░░░░▄███████▌░░░░░░░▒
▒░░░░░░░░░░░░░░░░░░░░░░░░▄█████████░░░░░░░░▒
▒░░░░░░░░░░░░░░░░░░░░░▄███████████▌░░░░░░░░▒
▒░░░░░░░░░░░░░░░▄▄▄▄██████████████▌░░░░░░░░▒
▒░░░░░░░░░░░▄▄███████████████████▌░░░░░░░░░▒
▒░░░░░░░░░▄██████████████████████▌░░░░░░░░░▒
▒░░░░░░░░████████████████████████░░░░░░░░░░▒
▒█░░░░░▐██████████▌░▀▀███████████░░░░░░░░░░▒
▐██░░░▄██████████▌░░░░░░░░░▀██▐█▌░░░░░░░░░▒▒
▒██████░█████████░░░░░░░░░░░▐█▐█▌░░░░░░░░░▒▒
▒▒▀▀▀▀░░░██████▀░░░░░░░░░░░░▐█▐█▌░░░░░░░░▒▒▒
▒▒▒▒▒░░░░▐█████▌░░░░░░░░░░░░▐█▐█▌░░░░░░░▒▒▒▒
▒▒▒▒▒▒░░░░███▀██░░░░░░░░░░░░░█░█▌░░░░░░▒▒▒▒▒
▒▒▒▒▒▒▒▒░▐██░░░██░░░░░░░░▄▄████████▄▒▒▒▒▒▒▒▒
▒▒▒▒▒▒▒▒▒██▌░░░░█▄░░░░░░▄███████████████████
▒▒▒▒▒▒▒▒▒▐██▒▒░░░██▄▄███████████████████████
▒▒▒▒▒▒▒▒▒▒▐██▒▒▄████████████████████████████
▒▒▒▒▒▒▒▒▒▒▄▄████████████████████████████████
████████████████████████████████████████████


                      ''')

print("\033[0;91m╔████████████"+"\033[0;92m▒▒▒▒▒▒▒▒▒▒▒▒▒▒"+"\033[0;93m████████████╗")
fnk=input("\033[0;93mFirst Name Kabital ›› ")
print("\033[0;94mFirst Name Kabital ➬ "+fnk)
time.sleep(.3)
lnk=input("\033[0;92mLast Name Kabital ›› ")
print("\033[0;91mLast Name Kabital ➬ "+lnk)
time.sleep(.3)
fn=input("\033[0;91mFirst Name ›› ")
time.sleep(.3)
print("\033[0;92mFirst name ➭",fn)
ln=input("fhather name ›› ")
time.sleep(.3)
print("\033[0;93mfhather name ➯",ln)
nm=input ("phone number ›› ")
time.sleep(.3)
print("\033[0;94mphone number ➱",nm)
bd=input("year of berth ›› ")
time.sleep(.3)
print("\033[0;95myear of berth ➫",bd)
time.sleep(.3)
mn=input("\033[0;96mmonth of berth ›› ")
print("month of berth ➭",mn)
time.sleep(.3)
da=input("\033[0;97mday of berth ›› ")
print("day of berth ➮ ",da)
time.sleep(1)

di=("\033[0;93m⚠")
os.system("clear")
print("\033[0;93mloding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")
print("loding...\ ",di)
time.sleep(.2)
os.system("clear")
print("loding.../ ",di)
time.sleep(.2)
os.system("clear")
print("loding...- ",di)
time.sleep(.2)
os.system("clear")

time.sleep(.3)

print ('''\033[0;32m    
Done...!

password is cracked !

your password is 

''')

time.sleep(.3)
lo=("\033[0;93m••¤(`×[¤")
go=("\033[0;93m¤]×´)¤••")
o=("\033[0;91m{")
oo=("\033[0;91m}")
print(lo,o,"\033[0;92m",fn+bd,oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",fn+ln+bd,oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",fn+ln+nm[0:4],oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",fn+nm[0:4],oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",nm,oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",fn+nm,oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",fn+da+mn+bd,oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",fn+ln+da+mn+bd,oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",fn[0:1]+nm,oo,go)
time.sleep(.2)
print(lo,o,"\033[0;92m",fn+ln+nm,oo,go)
time.sleep(.3)
print(lo,o,"\033[0;92m",fnk+lnk,oo,go)
time.sleep(.3)
print(lo,o,"\033[0;92m",fn+"1234",oo,go)
time.sleep (.3)
print(lo,o,"\033[0;92m",fn+ln+'000',oo,go)
time.sleep(.3)
print(lo,o,"\033[0;92m",fn+ln+'0000',oo,go)
time.sleep(.3)
print(lo,o,"\033[0;92m",'1122334455',oo,go)
print ('''\033[0;91mdont forget :
supscribe in youtube channel ♡
''')
input("cleck inter to restart: ")

time.sleep(.2)
os.system("xdg-open https://youtube.com/channel/UC8AxGnNNu8M4Q4fM0trOYyQ")
time.sleep(.3)
os.system("python passwords-hack.py")

